### ISSUE TITLE
Agregar validacion a campos de reserva antes de emitir petición al backend.

### ISSUE THREAD

**Issue by florpistan** [bautya10/SliceHaven-FrontEnd#67]
## Proceso
1. Ingrese a la pagina.
2. Me loguee con un usuario.
3. Intenté realizar una reserva sin completar todos los campos

## Resultado esperado
- El botón de hacer reserva se encuentra deshabilitado por defecto, recién se habilita cuando el usuario completó todos los datos del mismo, el frontend valida que los campos estén todos completos y en caso de ser así recién le habilita al usuario el botón de "hacer reserva" y la posibilidad de envíar la petición al backend, caso contrario, muestra mensaje de error al usuario indicandole que tiene que completar todos los campos antes de poder realizar un intento de reserva.

Resultado actual
- Al intentar realizar una reserva, el botón de realizar reserva se encuentra habilitado por defecto, sin haber completado todos los campos, el frontend no realiza ninguna validación y envía la petición al servidor.

## Evidencia

https://github.com/bautya10/SliceHaven-FrontEnd/assets/61049971/8f6d42e8-4201-4330-9012-054aee97a4db

**Comment by emilianogasco** [comment]
El proyecto esta pensado para que las reservas estén siempre actualizada.

En el hipotético caso de que dos usuarios realicen la misma reserva a la misma hora, el usuario que realizo al ultimo su reserva va a obtener la información nueva con la reserva ya ocupada, por eso hacemos la petición después de hacer clic en "hacer reservas" o al seleccionar otra hora o al selecciona la cantidad de personas.

La única forma de "silenciar" las horas o los días ocupados en la librería, es siempre haciendo la petición, ya que con los datos nuevos mostramos las horas y los días disponibles.

**Comment by florpistan** [comment]
@emilianogasco edité la issue para explicarte como debe ser el flujo.

Una aplicación de turnos/reservas debe realizar las validaciones en el servidor sí y solo sí la petición de reserva entrante cumple con la condición de ser una reserva **válida**. 

Una reserva **válida** es aquella que contiene los campos mínimos e indispensables para crear un nuevo evento, no podés intentar si quiera crear una reserva si solo tenés una fecha, no podes intentar crear una reserva si no sabes para cuantas personas va a ser. 

Tenés que intentar crear una reserva cuando el frontend te mande todos los datos necesarios para crear la misma, sino no tenés que dejar que el usuario mande la petición al servidor, para eso se utilizan las validaciones desde el fronted. Porque los gastos y la carga ocasionadas por peticiones que no cumplen con los requisitos minimos para pasar las validaciones del backend son innecesarios, se pueden evitar tranquilamente haciendo el trabajo de validar los campos en el frontend antes de enviar una petición al server.

Para manejar las reservas en caso de que dos personas diferentes quieran crear una el mismo día, primero tenés que ver si te quedan mesas disponibles para la cantidad de personas que quieren reservar, porque si sos un restaurante no tenés una sola mesa. En cualquiera de los casos el backend se va a encargar de:
 1- validar que la data de reserva corresponda a una reserva válida, que sea para una fecha futura(nunca pasada) y 
 2- que haya lugar disponible -> si hay lugar disponible se crea exitosamente la reserva, si no hay lugar, se retorna mensaje de error.

**Comment by florpistan** [comment]
Fixed! ✔🎉
